CREATE TABLE IF NOT EXISTS client (
    id       VARCHAR(20)  NOT NULL,
    name     VARCHAR(120) NOT NULL,
    type     VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS account (
    id                VARCHAR(20) NOT NULL,
    client_id         VARCHAR(20) NOT NULL,
    status            VARCHAR(10) NOT NULL,
    available_balance BIGINT      NOT NULL,
    version           BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT fk_account_client FOREIGN KEY (client_id) REFERENCES client(id)
);

CREATE TABLE IF NOT EXISTS transfer (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_reference      VARCHAR(50)  NOT NULL,
    source_account_id      VARCHAR(20)  NOT NULL,
    destination_account_id VARCHAR(20)  NOT NULL,
    amount                 BIGINT       NOT NULL,
    status                 VARCHAR(10)  NOT NULL,
    reason                 VARCHAR(120),
    processed_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_transfer_request_reference UNIQUE (request_reference)
);

CREATE INDEX IF NOT EXISTS idx_transfer_processed_at ON transfer (processed_at DESC);